//Mplan recharge plan fetch api
export const plans = {
  records: {
    FULLTT: [
      {
        rs: '48',
        desc: 'Gaming - Benefits: \n1.Unlimited Data (10MB 4G/5G Data, thereafter unlimited at 64Kbps)\n2. Subscription to JioGamesCloud\n3. Validity - 3 days',
        validity: '3 days',
        last_update: '04-01-2026',
      },
      {
        rs: '77',
        desc: 'Popular Plans - Benefits: \n1. Unlimited Data ( 3GB 4G/5G data thereafter unlimited at 64Kbps).\n2. Subscription to Sony LIV for 30 Days\n3. Data pack validity - 5 days\nNote - To access SonyLIV premium content, click https://tv.media.jio.com/extras/dl.html?jioplay://tab/24',
        validity: '5 days',
        last_update: '04-01-2026',
      },
      {
        rs: '98',
        desc: 'Gaming - Benefits: \n1.Unlimited Data (10MB 4G/5G Data, thereafter unlimited at 64Kbps)\n2. Subscription to JioGamesCloud\n3. Validity - 7 days',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '100',
        desc: 'Popular Plans - Benefits: 5 GB 4G/5G Data thereafter unlimited at 64 kbps, Jio Hotstar 1 month Subscription, Validity - 30 days. Note - To Activate Jio Hotstar Subscription: 1) Download the Jio Hotstar app. 2) LOG IN using OTP from your eligible Jio number. For more details click http://tiny.jio.com/r457tjI T&C Apply.',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '189',
        desc: 'Value - Benefits: Unlimited Voice, Unlimited data - 2GB, 300 SMS & Subscription to Jio Apps. Validity - 28 Days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '196',
        desc: 'Value - Benefits:\n 1) ICR Voice-1000 Mins\n 2) ICR Data-2 GB\n 3)1000 SMS \nValidity- 28 Days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '198',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 28GB(2GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 14 Days',
        validity: '14 days',
        last_update: '04-01-2026',
      },
      {
        rs: '239',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 33GB(1.5GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 22 Days',
        validity: '22 days',
        last_update: '04-01-2026',
      },
      {
        rs: '298',
        desc: 'Gaming - Benefits: \n1.Unlimited Data (3GB 4G/5G Data, thereafter unlimited at 64Kbps)\n2. Subscription to JioGamesCloud\n3. Validity - 28 days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '299',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 42GB(1.5GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 28 Days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '319',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 1.5GB/Day, 100 SMS/Day & Subscription to Jio Apps. Validity - 1 Month',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '329',
        desc: 'Popular Plans - Benefits: \n1. UNLIMITED DATA - 42 GB (1.5GB/Day)\n2. UNLIMITED Voice Calls\n3. 100 SMS/Day\n4. Subscription to JioApps and JioSaavn Pro\nValidity - 28 days\nNote - To activate JioSaavn Pro subscription, download app & login with your Jio number. https://jiosaa.vn/89b570ac',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '349',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 56GB(2GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 28 Days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '355',
        desc: 'Popular Plans - Benefits: \n1. Unlimited Data - 25GB\n2. Unlimited Voice Calls\n3. 100 SMS/Day\n4. Complimentary subscription to Jio Apps\nValidity - 30 Days',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '396',
        desc: 'Value - Benefits: \n1) ICR Voice-1000 Mins\n 2) ICR Data-10 GB\n 3)1000 SMS\n Validity- 28 Days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '399',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 70GB(2.5GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 28 Days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '445',
        desc: 'Popular Plans - Benefits: 1) Unlimited 5G Data, 56GB (2GB/Day 4G Data).  2) Unlimited Voice Calls. 3) 100 SMS/Day. 4) Complimentary subscription to Jio Apps. 5) Subscription to 11 Premium OTT apps. Validity - 28 days. Note - 1) To know how to watch premium content, click https://tiny.jio.com/JioTVPremiumPlan    2) Your plan needs to be in active state to start subscription',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '448',
        desc: 'Value - Benefits: Unlimited Voice,  1000 SMS & Subscription to Jio Apps. Validity - 84 Days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '449',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 84GB(3GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 28 Days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '450',
        desc: 'Popular Plans - Benefits: Unlimited 5G data, 72GB(2GB/Day 4G Data), Unlimited Voice, 100 SMS/Day & Subscription to Jio Apps. Validity - 36 Days',
        validity: '36 days',
        last_update: '04-01-2026',
      },
      {
        rs: '495',
        desc: 'Gaming - Benefits: \n1. Unlimited Data - 47GB (1.5 GB/Day + 5GB) 4G/5G Data\n2. Unlimited Voice\n3. 100 SMS/Day\n4.  Subscription to Jio Apps\n5. Subscription to JioGamesCloud\n6.Subscription to Fancode\n7. Validity - 28 days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '500',
        desc: 'Popular Plans - Benefits: 1) Unlimited 5G data & 2GB/Day 4G Data\n2)Unlimited Voice\n3)100 SMS/Day\n4) Subscription to YouTube Premium, JioHotstar, Amazon PVME, SonyLIV, ZEE5, Liongate Play, Discovery+ , SunNXT, Kanchha Lannka , Planet Marathi, Chaupal, FanCode and Hoichoi via JioTV and Jio Apps. \n5) Validity - 28 Days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '545',
        desc: 'Gaming - Benefits: \n1.  Unlimited 5G data, 61GB (2GB/Day 4G data + 5GB 4G data)\n2. Unlimited Voice\n3. 100 SMS/Day\n4. Subscription to Jio Apps\n5. Subscription to JioGamesCloud\n6.Subscription to Fancode\n7. Validity - 28 days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '579',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 84GB(1.5GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 56 Days',
        validity: '56 days',
        last_update: '04-01-2026',
      },
      {
        rs: '629',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 112GB(2GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 56 Days',
        validity: '56 days',
        last_update: '04-01-2026',
      },
      {
        rs: '666',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 105GB(1.5GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 70 Days',
        validity: '70 days',
        last_update: '04-01-2026',
      },
      {
        rs: '719',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 140GB(2GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 70 Days',
        validity: '70 days',
        last_update: '04-01-2026',
      },
      {
        rs: '749',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 164GB(2GB/Day+20GB), 100 SMS/Day & Subscription to Jio Apps. Validity - 72 Days',
        validity: '72 days',
        last_update: '04-01-2026',
      },
      {
        rs: '799',
        desc: 'Value - Benefits: Unlimited Voice, Unlimited data - 126GB(1.5GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 84 Days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '859',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 168GB(2GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 84 Days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '889',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 126GB(1.5GB/Day), 100 SMS/Day & Subscription to Jio Apps and JioSaavn Pro. Validity - 84 Days. Note - To activate JioSaavn Pro subscription, download app & login with your Jio number. https://jiosaa.vn/89b570ac',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '899',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 200GB (2GB/Day+20GB), 100 SMS/Day & Subscription to Jio Apps. Validity - 90 Days',
        validity: '90 days',
        last_update: '04-01-2026',
      },
      {
        rs: '949',
        desc: 'Popular Plans - Benefits: \n1. Unlimited 5G Data, 168GB (2GB/Day 4G Data)\n2. Unlimited Voice Calls\n3. JioHotstarMobile Subscription\n4. 100 SMS/Day\n5. Complimentary subscription to Jio Apps\nValidity - 84 days\nNote - To Activate JioHotstarMobile Subscription:\n1. Download the JioHotstarapp\n2. LOG IN using OTP from your eligible Jio number\nFor more details click http://tiny.jio.com/r457tjI T&C Apply.',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '999',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 196GB(2GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 98 Days',
        validity: '98 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1028',
        desc: 'Popular Plans - Benefits: \n1. UNLIMITED DATA - 168GB (2GB/Day) \n2. UNLIMITED CALLS\n3. 100 SMS/Day\n4. Complimentary Jio Apps\n5. Swiggy One Lite 3 Month Subscription\nValidity - 84 days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1029',
        desc: 'Popular Plans - Benefits: \n1. Unlimited Data - 168GB (2GB/Day)\n2. Unlimited Voice Calls\n3. Amazon Prime Video Mobile Edition- Included.\n4. 100 SMS/Day\n5. Complimentary subscription to Jio Apps\nValidity - 84 days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1049',
        desc: 'Popular Plans - Benefits: \n1. Unlimited Data - 168GB (2GB/Day)\n2. Unlimited Voice Calls\n3. 100 SMS/Day\n4. Complimentary subscription to Jio Apps\n5.Subscription to Zee5 & SonyLiv\nValidity - 84 days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1199',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 252GB(3GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 84 Days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1299',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 168GB(2GB/Day), 100 SMS/Day & Subscription to Jio Apps & Netflix (Mobile). Validity - 84 Days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1748',
        desc: 'Value - Benefits: Unlimited Voice,  3600 SMS & Subscription to Jio Apps. Validity - 336 Days',
        validity: '336 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1799',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 252GB(3GB/Day), 100 SMS/Day & Subscription to Jio Apps & Netflix (Basic). Validity - 84 Days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '2025',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 500GB(2.5GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 200 Days',
        validity: '200 days',
        last_update: '04-01-2026',
      },
      {
        rs: '3599',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 912.5GB(2.5GB/Day), 100 SMS/Day & Subscription to Jio Apps. Validity - 365 Days',
        validity: '365 days',
        last_update: '04-01-2026',
      },
      {
        rs: '3999',
        desc: 'Popular Plans - Benefits: Unlimited Voice, Unlimited data - 912.5GB(2.5GB/Day), 100 SMS/Day & Subscription to Jio Apps & FanCode. Validity - 365 Days',
        validity: '365 days',
        last_update: '04-01-2026',
      },
    ],
    TOPUP: [
      {
        rs: '10',
        desc: 'Top-up - Benefits: Rs. 7.47 Rs Monetary Talktime.',
        validity: 'N/A',
        last_update: '04-01-2026',
      },
      {
        rs: '20',
        desc: 'Top-up - Benefits: Rs. 14.95 Rs Monetary Talktime.',
        validity: 'N/A',
        last_update: '04-01-2026',
      },
      {
        rs: '50',
        desc: 'Top-up - Benefits: Rs. 39.37 Rs Monetary Talktime.',
        validity: 'N/A',
        last_update: '04-01-2026',
      },
      {
        rs: '1000',
        desc: 'Top-up - Benefits: Rs. 844.46 Rs Monetary Talktime.',
        validity: 'N/A',
        last_update: '04-01-2026',
      },
    ],
    '3G/4G': [
      {
        rs: '11',
        desc: 'Data Packs - Benefits: 1. Unlimited Data (10GB High Speed Data, thereafter unlimited at 64Kbps). Validity: 1 Hour',
        validity: '1 days',
        last_update: '04-01-2026',
      },
      {
        rs: '19',
        desc: 'Data Packs - Benefits: Unlimited Data (1GB High Speed Data, thereafter unlimited at 64Kbps). Validity: 1Day',
        validity: '1 days',
        last_update: '04-01-2026',
      },
      {
        rs: '29',
        desc: 'Data Packs - Benefits: Unlimited Data (2GB High Speed Data, thereafter unlimited at 64Kbps). Validity: 2Days',
        validity: '2 days',
        last_update: '04-01-2026',
      },
      {
        rs: '39',
        desc: 'Data Packs - Benefits: 1. Unlimited Data( 3GB/Day  4G/5G data thereafter unlimited at 64Kbps). Validity: 3 Days',
        validity: '3 days',
        last_update: '04-01-2026',
      },
      {
        rs: '49',
        desc: 'Data Packs - Benefits: 1. Unlimited Data (25GB High Speed Data, thereafter unlimited at 64Kbps).\nValidity: 1 day',
        validity: '1 days',
        last_update: '04-01-2026',
      },
      {
        rs: '51',
        desc: 'True Unlimited Upgrade - Benefits: 3GB High Speed data and Unlimited 5G Data. Validity: Base Plans validity',
        validity: 'N/A',
        last_update: '04-01-2026',
      },
      {
        rs: '69',
        desc: 'Data Packs - Benefits: Unlimited Data (6GB 4G/5G Data) thereafter unlimited at 64Kbps. Validity:  7 days',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '77',
        desc: 'Data Packs - Benefits: \n1. Unlimited Data ( 3GB 4G/5G data thereafter unlimited at 64Kbps).\n2. Subscription to Sony LIV for 30 Days\n3. Data pack validity - 5 days\nNote - To access SonyLIV premium content, click https://tv.media.jio.com/extras/dl.html?jioplay://tab/24',
        validity: '5 days',
        last_update: '04-01-2026',
      },
      {
        rs: '100',
        desc: 'Data Packs - Benefits: 5 GB 4G/5G Data thereafter unlimited at 64 kbps, Jio Hotstar 1 month Subscription, Validity - 30 days. Note - To Activate Jio Hotstar Subscription: 1) Download the Jio Hotstar app. 2) LOG IN using OTP from your eligible Jio number. For more details click http://tiny.jio.com/r457tjI T&C Apply.',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '101',
        desc: 'True Unlimited Upgrade - Benefits: 6GB High Speed data and Unlimited 5G Data. Validity: Base Plans validity',
        validity: 'N/A',
        last_update: '04-01-2026',
      },
      {
        rs: '103',
        desc: 'Data Packs - Benefits: 1. Unlimited Data -5 GB / 28 days  2. Select any pne Premium OTT apps bundle as per your choice on MyJio from :\n1. Hindi Entertainment :JioHotstar, SonyLIV, Zee5.\n2. International Entertainment :JioHotstar, FANCODE, LionsGate, Discovery+.\n3. Regional Entertainment: JioHotstar, SunNXT, Kancha Lanka, HoiChoi.\n\nNote : OTT bundle is valid for 28 days from the date of redemption.',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '139',
        desc: 'Data Packs - Benefits: Unlimited Data (12GB 4G/5G Data thereafter unlimited at 64Kbps). Validity: 7 days',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '151',
        desc: 'True Unlimited Upgrade - Benefits: 9GB High Speed data and Unlimited 5G Data. Validity: Base Plans validity',
        validity: 'N/A',
        last_update: '04-01-2026',
      },
      {
        rs: '175',
        desc: 'Data Packs - Benefits: 1. Unlimited Data (10GB High Speed Data, thereafter unlimited at 64Kbps).\n2. Subscription to 12 Premium OTT apps\nValidity: 28 days\nNote - 1. To know how to watch premium content, click\nhttps://tiny.jio.com/JioTVPremiumPlan\n2. Your plan needs to be in active state to start subscription',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '195',
        desc: 'Data Packs - Benefits: 15 GB 4G/5G Data thereafter unlimited at 64 kbps, JioHotstarMobile Subscription, Validity - 90 days. Note - To Activate JioHotstarMobile Subscription: 1) Download the JioHotstarapp. 2) LOG IN using OTP from your eligible Jio number. For more details click http://tiny.jio.com/r457tjI T&C Apply.',
        validity: '90 days',
        last_update: '04-01-2026',
      },
      {
        rs: '219',
        desc: 'Data Packs - Benefits: Unlimited Data (30GB High Speed Data, thereafter unlimited at 64Kbps). Validity: 30Days',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '289',
        desc: 'Data Packs - Benefits: Unlimited Data (40GB High Speed Data, thereafter unlimited at 64Kbps). Validity: 30Days',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '359',
        desc: 'Data Packs - Benefits: Unlimited Data (50GB High Speed Data, thereafter unlimited at 64Kbps). Validity: 30Days',
        validity: '30 days',
        last_update: '04-01-2026',
      },
    ],
    'RATE CUTTER': [
      {
        rs: '99',
        desc: 'JioSaavn Pro - Benefits: \r\nJIO SAVAN PRO\r\nValidity - 30 days\r\nNote - To Activate JioSaavn Premium Monthly Subscription visit JioSaavn App.',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '100',
        desc: 'Entertainment Plans - Benefits: 5 GB 4G/5G Data thereafter unlimited at 64 kbps, Jio Hotstar 1 month Subscription, Validity - 30 days. Note - To Activate Jio Hotstar Subscription: 1) Download the Jio Hotstar app. 2) LOG IN using OTP from your eligible Jio number. For more details click http://tiny.jio.com/r457tjI T&C Apply.',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '175',
        desc: 'Entertainment Plans - Benefits: 1. Unlimited Data (10GB High Speed Data, thereafter unlimited at 64Kbps).\n2. Subscription to 12 Premium OTT apps\nValidity: 28 days\nNote - 1. To know how to watch premium content, click\nhttps://tiny.jio.com/JioTVPremiumPlan\n2. Your plan needs to be in active state to start subscription',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '195',
        desc: 'Entertainment Plans - Benefits: 15 GB 4G/5G Data thereafter unlimited at 64 kbps, JioHotstarMobile Subscription, Validity - 90 days. Note - To Activate JioHotstarMobile Subscription: 1) Download the JioHotstarapp. 2) LOG IN using OTP from your eligible Jio number. For more details click http://tiny.jio.com/r457tjI T&C Apply.',
        validity: '90 days',
        last_update: '04-01-2026',
      },
      {
        rs: '329',
        desc: 'Entertainment Plans - Benefits: \n1. UNLIMITED DATA - 42 GB (1.5GB/Day)\n2. UNLIMITED Voice Calls\n3. 100 SMS/Day\n4. Subscription to JioApps and JioSaavn Pro\nValidity - 28 days\nNote - To activate JioSaavn Pro subscription, download app & login with your Jio number. https://jiosaa.vn/89b570ac',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '399',
        desc: 'JioSaavn Pro - Benefits: \r\nJIO SAVAN PRO\r\nValidity - 365 days\r\nNote - To Activate JioSaavn Premium Annual Subscription visit JioSaavn App.',
        validity: '365 days',
        last_update: '04-01-2026',
      },
      {
        rs: '445',
        desc: 'Entertainment Plans - Benefits: 1) Unlimited 5G Data, 56GB (2GB/Day 4G Data).  2) Unlimited Voice Calls. 3) 100 SMS/Day. 4) Complimentary subscription to Jio Apps. 5) Subscription to 11 Premium OTT apps. Validity - 28 days. Note - 1) To know how to watch premium content, click https://tiny.jio.com/JioTVPremiumPlan    2) Your plan needs to be in active state to start subscription',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '500',
        desc: 'Entertainment Plans - Benefits: 1) Unlimited 5G data & 2GB/Day 4G Data\n2)Unlimited Voice\n3)100 SMS/Day\n4) Subscription to YouTube Premium, JioHotstar, Amazon PVME, SonyLIV, ZEE5, Liongate Play, Discovery+ , SunNXT, Kanchha Lannka , Planet Marathi, Chaupal, FanCode and Hoichoi via JioTV and Jio Apps. \n5) Validity - 28 Days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '699',
        desc: 'JioLink - JioLink - MRP 699 Plan Benefits:  156GB Unlimited Data (5GB/Day + 16GB Additional Data), thereafter @64kbps and Complimentary Subscription to Jio Apps. Validity 28 Days',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '889',
        desc: 'Entertainment Plans - Benefits: Unlimited Voice, Unlimited data - 126GB(1.5GB/Day), 100 SMS/Day & Subscription to Jio Apps and JioSaavn Pro. Validity - 84 Days. Note - To activate JioSaavn Pro subscription, download app & login with your Jio number. https://jiosaa.vn/89b570ac',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '949',
        desc: 'Entertainment Plans - Benefits: \n1. Unlimited 5G Data, 168GB (2GB/Day 4G Data)\n2. Unlimited Voice Calls\n3. JioHotstarMobile Subscription\n4. 100 SMS/Day\n5. Complimentary subscription to Jio Apps\nValidity - 84 days\nNote - To Activate JioHotstarMobile Subscription:\n1. Download the JioHotstarapp\n2. LOG IN using OTP from your eligible Jio number\nFor more details click http://tiny.jio.com/r457tjI T&C Apply.',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1029',
        desc: 'Entertainment Plans - Benefits: \n1. Unlimited Data - 168GB (2GB/Day)\n2. Unlimited Voice Calls\n3. Amazon Prime Video Mobile Edition- Included.\n4. 100 SMS/Day\n5. Complimentary subscription to Jio Apps\nValidity - 84 days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1049',
        desc: 'Entertainment Plans - Benefits: \n1. Unlimited Data - 168GB (2GB/Day)\n2. Unlimited Voice Calls\n3. 100 SMS/Day\n4. Complimentary subscription to Jio Apps\n5.Subscription to Zee5 & SonyLiv\nValidity - 84 days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1299',
        desc: 'Entertainment Plans - Benefits: Unlimited Voice, Unlimited data - 168GB(2GB/Day), 100 SMS/Day & Subscription to Jio Apps & Netflix (Mobile). Validity - 84 Days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1799',
        desc: 'Entertainment Plans - Benefits: Unlimited Voice, Unlimited data - 252GB(3GB/Day), 100 SMS/Day & Subscription to Jio Apps & Netflix (Basic). Validity - 84 Days',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '3999',
        desc: 'Entertainment Plans - Benefits: Unlimited Voice, Unlimited data - 912.5GB(2.5GB/Day), 100 SMS/Day & Subscription to Jio Apps & FanCode. Validity - 365 Days',
        validity: '365 days',
        last_update: '04-01-2026',
      },
    ],
    '2G': [
      {
        rs: '26',
        desc: 'JioPhone Data Add-on - Benefits: \nUNLIMITED DATA - 2GB\nValidity - 28 days\nOnly for JioPhones',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '62',
        desc: 'JioPhone Data Add-on - Benefits: \nUNLIMITED DATA - 6GB\nValidity - 28 days\nOnly for JioPhones',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '75',
        desc: 'JioPhone - Benefits: \n1. UNLIMITED DATA - 2.5GB (100 MB/Day + 200MB) \n2. UNLIMITED CALLS\n3. 50SMS\n4. Complimentary Jio Apps\nValidity - 23 days\nOnly for JioPhones',
        validity: '23 days',
        last_update: '04-01-2026',
      },
      {
        rs: '86',
        desc: 'JioPhone Data Add-on - Benefits: \nUNLIMITED DATA - 0.5GB/Day\nValidity - 28 days\nOnly for JioPhones',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '91',
        desc: 'JioPhone - Benefits: \n1. UNLIMITED DATA - 3GB (100 MB/Day + 200MB) \n2. UNLIMITED CALLS\n3. 50SMS\n4. Complimentary Jio Apps\nValidity - 28 days\nOnly for JioPhones',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '122',
        desc: 'JioPhone Data Add-on - Benefits: \nUNLIMITED DATA - 1GB/Day\nValidity - 28 days\nOnly for JioPhones',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '123',
        desc: 'JioBharat Phone - Benefits: \n1. UNLIMITED DATA - 14 GB (0.5GB/Day)\n2. UNLIMITED Voice Calls\n3. 300 SMS\n4. Subscription to JioApps\nValidity - 28 days\nOnly for Jio Bharat Phones',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '125',
        desc: 'JioPhone - Benefits: \n1. UNLIMITED DATA - 11.5GB (0.5GB/Day)\n2. UNLIMITED CALLS\n3. 300SMS\n4. Complimentary Jio Apps\nValidity - 23 days\nOnly for JioPhones',
        validity: '23 days',
        last_update: '04-01-2026',
      },
      {
        rs: '152',
        desc: 'JioPhone - Benefits: \n1. UNLIMITED DATA - 14GB (0.5GB/Day)\n2. UNLIMITED CALLS\n3. 300SMS\n4. Complimentary Jio Apps\nValidity - 28 days\nOnly for JioPhones',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '182',
        desc: 'JioPhone Data Add-on - Benefits: \nUNLIMITED DATA - 2GB/Day\nValidity - 28 days\nOnly for JioPhones',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '186',
        desc: 'JioPhone - Benefits: \n1. UNLIMITED DATA - 28GB (1GB/Day)\n2. UNLIMITED CALLS\n3. 100SMS/day\n4. Complimentary Jio Apps\nValidity - 28 days\nOnly for JioPhones',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '223',
        desc: 'JioPhone - Benefits: \n1. UNLIMITED DATA - 56GB (2GB/Day)\n2. UNLIMITED CALLS  \n3. 100SMS/day\n4. Complimentary Jio Apps\nValidity - 28 days\nOnly for JioPhones',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '234',
        desc: 'JioBharat Phone - Benefits: \n1. UNLIMITED DATA - 28 GB (0.5GB/Day)\n2. UNLIMITED Voice Calls\n3. 300 SMS/28 days\n4. Subscription to JioApps\nValidity - 56 days\nOnly for Jio Bharat Phones',
        validity: '56 days',
        last_update: '04-01-2026',
      },
      {
        rs: '369',
        desc: 'JioBharat Phone - Benefits: \n1. UNLIMITED DATA - 42 GB (0.5GB/Day)\n2. UNLIMITED Voice Calls\n3. 300 SMS/28 Days\n4. Subscription to JioApps\nValidity - 84 days\nOnly for Jio Bharat Phones',
        validity: '84 days',
        last_update: '04-01-2026',
      },
      {
        rs: '895',
        desc: 'JioPhone - Benefits: \n1. UNLIMITED DATA - 2GB / Month\n2. Unlimited Voice calls\n3. 50 SMS / Month\n4. Complimentary Jio Apps Subscription\nValidity - 28 days * 12 Cycles\nOnly for JioPhones',
        validity: '336 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1234',
        desc: 'JioBharat Phone - Benefits: \n1. UNLIMITED DATA - 168 GB (0.5GB/Day)\n2. UNLIMITED Voice Calls\n3. 300 SMS/28 days\n4. Subscription to JioApps\nValidity - 336 days\nOnly for Jio Bharat Phones',
        validity: '336 days',
        last_update: '04-01-2026',
      },
    ],
    Romaing: [
      {
        rs: '38',
        desc: 'ISD - Benefit - 30 Minutes calls to USA & Canada. Validity - 7 Days',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '47',
        desc: 'ISD - Benefit - 15 Minutes ISD calls to Bangladesh. Validity - 7 Days',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '59',
        desc: 'ISD - Benefit - 15 Minutes calls to Singapore, Thailand, Malaysia & Hong kong. Validity - 7 Days',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '74',
        desc: 'ISD - Benefit - 15 Minutes ISD calls to Australia & New Zealand. Validity - 7 Days',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '79',
        desc: 'ISD - Benefit - 10 Minutes calls to United Kingdom, Germany, France & Spain. Validity - 7 Days',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '89',
        desc: 'ISD - Benefit - 15 Minutes calls to China, Japan & Bhutan. Validity - 7 Days',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '99',
        desc: 'ISD - Benefit - 10 Minutes calls to UAE, Saudi Arabia, Turkey, Kuwait & Bahrain. Validity - 7 Days',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '121',
        desc: 'IR Wi-Fi Calling - Benefits : Voice - 100 mins (For Outgoing Wi-Fi Calls to India Only + Incoming Wi-Fi call from anywhere). Beyond FUP, Incoming calls from any country at ¿ 1/Min, Outgoing calls to India at ¿ 1 /Min.  This pack will only work if your handset supports Wi-Fi Calling. To check handset compatibility, visit: bit.ly/3r6jx8a\nThis pack can be used for making Wi-Fi outgoing calls to India ONLY and incoming Wi-Fi calls can be received from anywhere.\nOutgoing calls/SMS to Local/ROW are NOT allowed in this pack.\nValidity: 10 days\nTo know more about How To Enable Wi-Fi Calling, please visit: bit.ly/3JB5qxX',
        validity: '2 days',
        last_update: '04-01-2026',
      },
      {
        rs: '195',
        desc: 'In-Flight Packs - Benefits : 100 Voice outgoing minutes , Voice Incoming calls Not allowed, 100 SMS, 250 MB High Speed Data .Voice data and SMS service availability will differ from airline to airline.\nValidity: 1 day\nFor the list of Airlines and In-Flight communication services available visit: https://t.ly/NLkcT',
        validity: '1 days',
        last_update: '04-01-2026',
      },
      {
        rs: '295',
        desc: 'In-Flight Packs - Benefits : 100 Voice outgoing minutes , Voice Incoming calls Not allowed, 100 SMS, 500 MB High Speed Data .Voice data and SMS service availability will differ from airline to airline.\nValidity: 1 day\nFor the list of Airlines and In-Flight communication services available visit: https://t.ly/NLkcT',
        validity: '1 days',
        last_update: '04-01-2026',
      },
      {
        rs: '499',
        desc: 'International Roaming - Benefits : 100 Voice outgoing minutes (Local calls + Calls to India), Voice Incoming calls Free (including Wi-Fi calls), 100 SMS, Data 250 MB High Speed Data for 32 Countries. Applicable on select partners and countries only. Beyond FUP, Incoming calls (including Wi-Fi calls) will be free until validity expires, data speed will be at 64kbps and for other benefits standard rates will be applicable.\nValidity: 1 day\nFor information on countries covered, partner networks visit: bit.ly/44qshod and for Standard Roaming rates, visit www.jio.com\nKindly note: If you have also purchased Roam More packs with Travel Pass then Roam More packs will get activated first.',
        validity: '1 days',
        last_update: '04-01-2026',
      },
      {
        rs: '501',
        desc: 'ISD - ISD Talktime: Rs. 424.58  and 5 ISD SMS, Talktime can be used only for making ISD calls and  ISD SMS while in India.\nValidity: 28 days.\nFor ISD Call rates, kindly visit www.jio.com',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '521',
        desc: 'IR Wi-Fi Calling - Benefits : Voice - 500 mins (For Wi-Fi Calls to India Only +  Incoming Wi-Fi call from anywhere). Beyond FUP, Incoming call from any country at ¿ 1/Min, Outgoing call to India at ¿ 1 /Min. This pack will only work if your handset supports Wi-Fi Calling. To check handset compatibility, visit: bit.ly/3r6jx8a\nThis pack can be used for making Wi-Fi outgoing calls to India ONLY and incoming Wi-Fi calls can be received from anywhere.\nOutgoing calls/SMS to Local/ROW are NOT allowed in this pack.\nValidity: 10 days\nTo know more about How To Enable Wi-Fi Calling, please visit: bit.ly/3JB5qxX\n',
        validity: '10 days',
        last_update: '04-01-2026',
      },
      {
        rs: '595',
        desc: 'In-Flight Packs - Benefits : 100 Voice outgoing minutes , Voice Incoming calls Not allowed, 100 SMS, 1 GB High Speed Data .Voice data and SMS service availability will differ from airline to airline.\nValidity: 1 day\nFor the list of Airlines and In-Flight communication services available visit: https://t.ly/NLkcT',
        validity: '1 days',
        last_update: '04-01-2026',
      },
      {
        rs: '891',
        desc: 'International Roaming - Benefits : Voice 100 minutes [Local calls + Calls to India (including Wi-Fi calls)], 100 Voice Incoming minutes (including Wi-Fi calls), 20 SMS and 2 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in Saudi Arabia only.\nValidity: 7 days\nFor information on Standard Roaming rates, visit www.jio.com',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '896',
        desc: 'International Roaming - Benefits : Voice 100 minutes [Local calls + Calls to India + ROW], 50 Voice Incoming minutes, 25 SMS and 2 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in Caribbean Islands only.\nValidity: 7 days\nFor information on countries covered, Standard Roaming rates and partner airlines, visit www.jio.com',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '898',
        desc: 'International Roaming - Benefits: 100 mins Outgoing calls [Local Calls + Calls to India (including Wi-Fi calls)], 100 mins Incoming calls (including Wi-Fi calls), 100 SMS, 1 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in UAE only.\nValidity: 7 days\nFor More information and partner networks visit: http://surl.li/nxprw',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '999',
        desc: 'International Roaming - Benefits : Data-1 GB High Speed Data for 70 countries. Beyond FUP, data speed will be at 64kbps until pack expiry.\nValidity: 7 days\nFor information on countries covered, partner networks visit: bit.ly/3CV7Xze and for Standard Roaming rates, visit www.jio.com',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1101',
        desc: 'International Roaming - Monetary value of Rs. 933.05  and 5 ISD SMS. Monetary Value can be used on International Roaming in select countries. \nValidity: 28 days.\nFor IR rates, kindly visit www.jio.com',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1102',
        desc: 'International Roaming - Monetary value of Rs. 933.90  and 5 ISD SMS. Monetary Value can be used on International Roaming in select countries. \nValidity: 28 days.\nFor IR rates, kindly visit www.jio.com',
        validity: '28 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1291',
        desc: 'International Roaming - Benefits : Voice 100 minutes [Local calls + Calls to India (including Wi-Fi calls)], 100 Voice Incoming minutes (including Wi-Fi calls), 50 SMS and 4 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in Saudi Arabia only.\nValidity: 14 days\nFor information on Standard Roaming rates, visit www.jio.com',
        validity: '14 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1499',
        desc: 'International Roaming - Benefits : Voice 100 minutes [Local calls + Calls to India (including Wi-Fi calls)]+ Incoming minutes (including Wi-Fi calls), 100 SMS and 2 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and standard pay-go rates will be applicable for all benefits. \nValidity: 14 days\nFor information on countries covered, Standard Roaming rates, visit www.jio.com',
        validity: '14 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1551',
        desc: 'International Roaming - Benefits : Voice 100 minutes [Local calls + Calls to India (including Wi-Fi calls)], 100 Voice Incoming minutes (including Wi-Fi calls), 50 SMS and 6 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack is valid only in Thailand, Singapore, Japan, South Korea, Hong Kong and Macau.\nValidity: 14 days\nFor information on Standard Roaming rates, visit www.jio.com',
        validity: '14 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1555',
        desc: 'International Roaming - Benefits: 150 mins Outgoing calls [Local Calls + Calls to India (including Wi-Fi calls)], Unlimited Incoming calls (including Wi-Fi calls), 100 SMS, 7 GB High Speed Data. Beyond FUP, Incoming calls (including Wi-Fi calls) will be free until validity expires, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in USA, Mexico and U.S.Virgin Islands only.\nValidity: 10 days\nFor More information and partner networks visit: http://surl.li/nxprw"',
        validity: '10 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1598',
        desc: 'International Roaming - Benefits: 150 mins Outgoing calls [Local Calls + Calls to India (including Wi-Fi calls)], 150 mins Incoming calls (including Wi-Fi calls), 100 SMS, 3 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in UAE only.\nValidity: 14 days\nFor More information and partner networks visit: http://surl.li/nxprw',
        validity: '14 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1671',
        desc: 'International Roaming - Benefits : Voice 150 minutes [Local calls + Calls to India + ROW], 50 Voice Incoming minutes, 50 SMS and 4 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in Caribbean Islands only.\nValidity: 14 days\nFor information on countries covered, Standard Roaming rates and partner airlines, visit www.jio.com',
        validity: '14 days',
        last_update: '04-01-2026',
      },
      {
        rs: '1691',
        desc: 'International Roaming - Benefits : Voice 100 minutes [Local calls + Calls to India (including Wi-Fi calls)], 100 Voice Incoming minutes (including Wi-Fi calls), 50 SMS and 5 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in Canada only.\nValidity: 14 days\nFor information on Standard Roaming rates, visit www.jio.com',
        validity: '14 days',
        last_update: '04-01-2026',
      },
      {
        rs: '2499',
        desc: 'International Roaming - Benefits: 100 mins Voice Outgoing (Local Calls+ Calls to India) , Unlimited Incoming calls (including Wi-Fi calls), 100 SMS, 250 MB High Speed Data per day thereafter unlimited at 64kbps. Beyond FUP, standard pay-go rates will be applicable for all benefits except for incoming calls and data until pack expiry. Pack includes Free 1 day Inflight Pass with 100 mins Outgoing, 250 MB data & 100 SMS, applicable in 22 airlines. Incoming calls not allowed in flight Pass.\nValidity: 10 days\nFor information on countries covered, partner networks visit: bit.ly/3NvvKuF and for Standard Roaming rates and partner airlines, visit www.jio.com',
        validity: '10 days',
        last_update: '04-01-2026',
      },
      {
        rs: '2555',
        desc: 'International Roaming - Benefits: 250 mins Outgoing calls [Local Calls + Calls to India (including Wi-Fi calls)], Free Voice Incoming calls (including Wi-Fi calls), 100 SMS, 15 GB High Speed Data. Beyond FUP, Incoming calls (including Wi-Fi calls) will be free until validity expires, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack valid in USA, Mexico and U.S. Virgin Islands only.\nValidity: 30 days\nFor More information visit: https://www.jio.com',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '2799',
        desc: 'International Roaming - Benefits : Voice 100 minutes [Local calls + Calls to India + Incoming calls (including Wi-Fi calling)] , 100 SMS, 2 GB High Speed Data for 51 Countries. Applicable on select partners and countries only. Beyond FUP, data speed will be at 64kbps and for other benefits Standard PayGo rates will be applicable.\nKindly note: This pack requires manual activation through MyJio and will not be activated on first usage. Go to Upcoming Plans in Myjio and activate this pack to use in IR.\nValidity: 365 days\nFor information on countries covered, partner networks visit: bit.ly/3NvvKuF and for Standard Roaming rates, visit www.jio.com',
        validity: '365 days',
        last_update: '04-01-2026',
      },
      {
        rs: '2851',
        desc: 'International Roaming - Benefits : Voice 150 minutes [Local calls + Calls to India (including Wi-Fi calls)], 150 Voice Incoming minutes (including Wi-Fi calls), 100 SMS and 12 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack is valid only in Thailand, Singapore, Japan, South Korea, Hong Kong and Macau.\nValidity: 30 days\nFor information on Standard Roaming rates, visit www.jio.com',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '2881',
        desc: 'International Roaming - Benefits : Voice 150 minutes [Local calls + Calls to India (including Wi-Fi calls)], 150 Voice Incoming minutes (including Wi-Fi calls), 100 SMS and 10 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in Canada only.\nValidity: 30 days\nFor information on Standard Roaming rates, visit www.jio.com',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '2888',
        desc: 'International Roaming - Benefits : Voice 150 minutes [Local calls + Calls to India + ROW], 50 Voice Incoming minutes, 100 SMS and 8 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in Caribbean Islands only.\nValidity: 30 days\nFor information on countries covered, Standard Roaming rates and partner airlines, visit www.jio.com',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '2891',
        desc: 'International Roaming - Benefits : Voice 150 minutes [Local calls + Calls to India (including Wi-Fi calls)], 150 Voice Incoming minutes (including Wi-Fi calls), 100 SMS and 10 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in Saudi Arabia only.\nValidity: 30 days\nFor information on Standard Roaming rates, visit www.jio.com',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '2899',
        desc: 'International Roaming - Benefits : Voice 100 minutes [Local calls + Calls to India (including Wi-Fi calls)], 100 Voice Incoming minutes (including Wi-Fi calls), 100 SMS and 5 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and standard pay-go rates will be applicable for all benefits. Pack includes Free 1 day Inflight Pass with 100 mins Outgoing, 250 MB data & 100 SMS, applicable in 22 airlines. Incoming calls not allowed in flight Pass.\nValidity: 30 days\nFor information on countries covered, Standard Roaming rates and partner airlines, visit www.jio.com',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '2998',
        desc: 'International Roaming - Benefits: 250 mins Outgoing calls [Local Calls + Calls to India (including Wi-Fi calls)], 250mins Incoming calls (including Wi-Fi calls), 100 SMS, 7 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable. Pack applicable in UAE only.\nValidity: 21 days\nFor More information and partner networks visit: http://surl.li/nxprw',
        validity: '21 days',
        last_update: '04-01-2026',
      },
      {
        rs: '2999',
        desc: 'International Roaming - Benefits : Data- 5 GB High Speed Data for 70 countries. Beyond FUP, data speed will be at 64kbps until pack expiry.\nValidity: 7 days\nFor information on countries covered, partner networks visit: bit.ly/3CV7Xze and for Standard Roaming rates, visit www.jio.com',
        validity: '7 days',
        last_update: '04-01-2026',
      },
      {
        rs: '3455',
        desc: 'International Roaming - Benefits: 250 mins Outgoing calls [Local Calls + Calls to India (including Wi-Fi calls)], Free Voice Incoming calls (including Wi-Fi calls), 100 SMS, 25 GB High Speed Data. Beyond FUP, Incoming calls (including Wi-Fi calls) will be free until validity expires, data speed will be at 64kbps and for other benefits standard pay-go rates will be applicable.Pack includes Free 1 day Inflight Pass with 100 mins Outgoing, 250 MB data & 100 SMS, applicable in 22 airlines. Incoming calls not allowed in flight Pass. Pack valid in USA, Mexico and U.S. Virgin Islands only.\nValidity: 35 days\nFor More information visit: https://www.jio.com\n',
        validity: '35 days',
        last_update: '04-01-2026',
      },
      {
        rs: '3851',
        desc: 'International Roaming - Benefits : Voice 200 minutes [Local calls + Calls to India + ROW], 50 Voice Incoming minutes , 100 SMS and 10 GB High Speed Data. Beyond FUP, data speed will be at 64kbps and for other sevice beyond benefits standard pay-go rates will be applicable. Pack applicable in Caribbean Islands only.\nValidity: 35 days\nFor information on countries covered, Standard Roaming rates and partner airlines, visit www.jio.com',
        validity: '35 days',
        last_update: '04-01-2026',
      },
      {
        rs: '3999',
        desc: 'International Roaming - Benefits: 250 mins Voice Outgoing (Local calls + Calls to India), Unlimited Incoming calls (including Wi-Fi calls), 100 SMS, 4 GB High Speed Data thereafter unlimited at 64kbps. Beyond FUP, standard pay-go rates will be applicable for all benefits except for incoming calls and data until pack expiry. Pack includes Free 1 day Inflight Pass with 100 mins Outgoing, 250 MB data & 100 SMS, applicable in 22 airlines. Incoming calls not allowed in flight Pass.\nValidity: 30 days\nFor information on countries covered, partner networks visit: bit.ly/3NvvKuF and for Standard Roaming rates and partner airlines, visit www.jio.com',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '4499',
        desc: 'International Roaming - Benefits : Data- 8 GB High Speed Data for 70 countries. Beyond FUP, data speed will be at 64kbps until pack expiry.\nValidity: 14 days\nFor information on countries covered, partner networks visit: bit.ly/3CV7Xze and for Standard Roaming rates, visit www.jio.com',
        validity: '14 days',
        last_update: '04-01-2026',
      },
      {
        rs: '4999',
        desc: 'International Roaming - Benefits: 1500 mins Voice Outgoing (Local calls + Calls to India), Unlimited Incoming calls (including Wi-Fi calls), 1500 SMS, 5 GB High Speed Data thereafter unlimited at 64kbps. Beyond FUP, standard pay-go rates will be applicable for all benefits except for incoming calls and data until pack expiry. Pack includes Free 1 day Inflight Pass with 100 mins Outgoing, 250 MB data & 100 SMS, applicable in 22 airlines. Incoming calls not allowed in flight Pass.\nValidity: 30 days\nFor information on countries covered, partner networks visit: bit.ly/3NvvKuF and for Standard Roaming rates and partner airlines, visit www.jio.com',
        validity: '30 days',
        last_update: '04-01-2026',
      },
      {
        rs: '5899',
        desc: 'International Roaming - Benefits : Data- 10 GB High Speed Data for 70 countries.Beyond FUP, data speed will be at 64kbps until pack expiry.\nValidity: 21 days\nFor information on countries covered, partner networks visit: bit.ly/3CV7Xze and for Standard Roaming rates, visit www.jio.com',
        validity: '21 days',
        last_update: '04-01-2026',
      },
      {
        rs: '5999',
        desc: 'International Roaming - Benefits: 400 mins Voice Outgoing (Local calls + Calls to India +Rest of the world), Unlimited Incoming calls (including Wi-Fi calls), 500 SMS, 6 GB High Speed Data thereafter unlimited at 64kbps. Beyond FUP, standard pay-go rates will be applicable for all benefits except for incoming calls and data until pack expiry. Pack includes Free 1 day Inflight Pass with 100 mins Outgoing, 250 MB data & 100 SMS, applicable in 22 airlines. Incoming calls not allowed in flight Pass.\nValidity: 30 days\nFor information on countries covered, partner networks visit: bit.ly/3NvvKuF and for Standard Roaming rates and partner airlines, visit www.jio.com',
        validity: '30 days',
        last_update: '04-01-2026',
      },
    ],
  },
  status: 1,
  time: 0.01993417739868164,
};

export const rechargeResponseData = {
  status: 'SUCCESS',
  message: 'Transaction Success',
  transid: 'REC28377449',
  optransid: '6207728071',
  referenceid: 654503821,
  number: '7070683011',
  amount: 10,
  balance: 0,
  margin: 0.44,
};
