export const PermissionsRegistryAdmin = {
  RECHARGE_ADMIN_OPERATORS: {
    CREATE: 'RECHARGE.ADMIN.OPERATORS.CREATE',
    READ: 'RECHARGE.ADMIN.OPERATORS.READ',
    UPDATE: 'RECHARGE.ADMIN.OPERATORS.UPDATE',
    DELETE: 'RECHARGE.ADMIN.OPERATORS.DELETE',
  },

  RECHARGE_ADMIN_CIRCLES: {
    CREATE: 'RECHARGE.ADMIN.CIRCLES.CREATE',
    READ: 'RECHARGE.ADMIN.CIRCLES.READ',
    UPDATE: 'RECHARGE.ADMIN.CIRCLES.UPDATE',
    DELETE: 'RECHARGE.ADMIN.CIRCLES.DELETE',
  },

  SERVICE: {
    CREATE: 'SERVICE.CREATE',
    READ: 'SERVICE.READ',
    UPDATE: 'SERVICE.UPDATE',
    DELETE: 'SERVICE.DELETE',
  },

  PROVIDER: {
    CREATE: 'PROVIDER.CREATE',
    READ: 'PROVIDER.READ',
    UPDATE: 'PROVIDER.UPDATE',
    DELETE: 'PROVIDER.DELETE',
  },

  MAPPING: {
    CREATE: 'MAPPING.CREATE',
    READ: 'MAPPING.READ',
    UPDATE: 'MAPPING.UPDATE',
    DELETE: 'MAPPING.DELETE',
  },

  SLAB: {
    CREATE: 'SLAB.CREATE',
    READ: 'SLAB.READ',
    UPDATE: 'SLAB.UPDATE',
    DELETE: 'SLAB.DELETE',
  },
};
