import { Router } from 'express';
import tenantRoutes from './tenant.routes.js';
import tenantDomainRoutes from './tenantDomain.routes.js';
import serverDetailRoutes from './serverDetail.routes.js';
import smtpConfigRoutes from './smtpConfig.routes.js';
import auditRoutes from './audit.routes.js';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import departmentRoutes from './department.routes.js';
import roleRoutes from './role.routes.js';
import employeeRoutes from './employee.routes.js';
import tenantWebsiteRoutes from './tenantWebsite.routes.js';
import tenantSocialMediaRoutes from './tenantSocialMedia.routes.js';
import rechargeRoutes from './recharge/recharge.routes.js';
import rechargeAdminRoutes from './recharge-admin/recharge-admin.routes.js';
import commisionRoutes from './commission.routes.js';
import permissionRoutes from './permission.routes.js';
import kycRoutes from './kyc.routes.js';
import fundRequestRoutes from './fund-request/fundTransaction.routes.js';
import serviceRoutes from './service.routes.js';
import statesCities from './state-city.routes.js';
import transactionsRoutes from './transaction.routes.js';
import ledgerRoutes from './ledger.routes.js';
import repostRoutes from './report.routes.js';
import bankRoutes from './bankDetail.routes.js';
import payoutRoutes from './payout/payout.routes.js';
import bankVerificationRoutes from './bank/bankVerification.routes.js';

const router = Router();

router.use('/tenants', tenantRoutes);
router.use('/tenant-domain', tenantDomainRoutes);
router.use('/server-detail', serverDetailRoutes);
router.use('/smtp-configs', smtpConfigRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/departments', departmentRoutes);
router.use('/employees', employeeRoutes);
router.use('/website', tenantWebsiteRoutes);
router.use('/social-media', tenantSocialMediaRoutes);
router.use('/admin', serviceRoutes);
router.use('/commission', commisionRoutes);
router.use('/recharge', rechargeRoutes);
router.use('/payout', payoutRoutes);
router.use('/', transactionsRoutes);
router.use('/ledger', ledgerRoutes);
router.use('/report', repostRoutes);
router.use('/admin/recharge', rechargeAdminRoutes);
router.use('/permissions', permissionRoutes);
router.use('/kyc', kycRoutes);
router.use('/bank', bankRoutes);
router.use('/bank-verification', bankVerificationRoutes);
router.use('/fund-request', fundRequestRoutes);
router.use('/state-city', statesCities);
export default router;
