export const ALLOWED_SERVICES_ROLES = [
  "STATE_HEAD",
  "MASTER_DISTRIBUTOR",
  "DISTRIBUTOR",
  "RETAILER",
];

export const PAYOUT_ALLOWED_SERVICES_ROLES = [
  "STATE_HEAD",
  "MASTER_DISTRIBUTOR",
  "DISTRIBUTOR",
  "RETAILER",
];

export const ADMIN_ROLE = "AZZUNIQUE";
